version: '3'
services:
  cassandra:
    image: cassandra:3.11.4
    ports:
      - "9042:9042"
  cadence:
    image: ubercadence/server:master-auto-setup
    ports:
     - "7933:7933"
     - "7934:7934"
     - "7935:7935"
     - "7939:7939"
    environment:
      - "CASSANDRA_SEEDS=cassandra"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
    depends_on:
      - cassandra
  cadence-web:
    image: ubercadence/web:3.4.1
    environment:
      - "CADENCE_TCHANNEL_PEERS=cadence:7933"
    ports:
      - "8088:8088"
    depends_on:
      - cadence
  db:
    image: postgres:11.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: cadetimeout
      POSTGRES_USER: cadetimeout
      POSTGRES_DB: cadetimeout
