server.port: 9091
spring:
  datasource:
    url: "jdbc:postgresql://localhost/questionmarks"
    username: cadetimeout
    password: cadetimeout
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false